const { performSearch } = require("../utils");

module.exports = {
  key: "person",
  noun: "Person",
  display: {
    label: "Find Person",
    description: "Finds a person by email, phone, or LinkedIn profile URL.",
  },
  operation: {
    // Don't let Zapier auto-trim/cast our string inputs — keep behavior predictable.
    cleanInputData: false,
    inputFields: [
      { key: "email", label: "Email", type: "string", helpText: "The person's email address." },
      { key: "phone", label: "Phone", type: "string", helpText: "The person's phone number." },
      { key: "profile_url", label: "Profile URL", type: "string", helpText: "The person's LinkedIn (or other) profile URL." },
    ],
    perform: performSearch("person"),
    // Mirrors the real /search?type=person response shape (trimmed), so Zapier's field
    // mapper offers the right nested paths (emails[].address, experiences[].company.domain, etc).
    sample: {
      id: 12345678,
      external_urls: ["http://janedoe.io"],
      emails: [{ address: "jane.doe@example.com", verified: false, type: "professional" }],
      phones: [{ number: "+12025550123", carrier: null, score: null, type: "mobile", country_code: "us" }],
      names: [{ first_name: "jane", middle_name: null, last_name: "doe", network: "linkedin" }],
      profiles: [
        {
          created_at: "2026-02-15T13:48:23.000Z",
          profile_created_at: "2015-07-06T20:47:15.000Z",
          type: "person",
          profile_id: null,
          username: "janedoe",
          url: "linkedin.com/in/janedoe",
          profile_picture: "https://stellarwind.expose.team/sample.jpg",
          cover_picture: null,
          verified: true,
          private: false,
          followers_count: 706,
          following_count: 275,
          posts_count: 42,
          groups_count: null,
          favourites_count: null,
          description: "Product manager & tech enthusiast.",
          network: "linkedin",
        },
      ],
      significant_dates: [{ day: 25, month: 5, year: 1990, network: "facebook", type: "birth" }],
      locations: [{ address: null, region: null, zip: null, time_zone: null, network: "linkedin", city: "san francisco", country: "united states", continent: "north america", state: "ca" }],
      vehicles: [],
      repositories: [],
      ads_ids: [],
      devices: [],
      physical_attribute: [],
      experiences: [
        {
          company_id: 3696872,
          start: "2020-05-01T00:00:00.000Z",
          end: null,
          title: "product manager",
          summary: null,
          decision_maker: true,
          company_name: "acme inc",
          current: true,
          level: null,
          department: null,
          employment_type: "full_time",
          company: {
            id: 3696872,
            domain: "acme.com",
            is_school: false,
            company_size_range: "51-200",
            founded: 2015,
            industries: ["software"],
            profiles: [{ url: "linkedin.com/company/acme", network: "linkedin" }],
            locations: [{ city: "san francisco", country: "united states", network: "internal" }],
            names: [{ first_name: "acme inc", middle_name: null, last_name: null, network: "linkedin" }],
          },
        },
      ],
      educations: [
        {
          school_id: 38127,
          start: "2011-01-01T00:00:00.000Z",
          end: "2015-01-01T00:00:00.000Z",
          degree: "bachelor's degree, computer science",
          major: "computer science",
          certification: false,
          summary: null,
          school_name: "stanford university",
          current: false,
          school: {
            id: 38127,
            domain: "stanford.edu",
            is_school: true,
            profiles: [{ url: "linkedin.com/school/stanford-university", network: "linkedin" }],
            names: [{ first_name: "stanford university", middle_name: null, last_name: null, network: "linkedin" }],
          },
        },
      ],
      languages: [{ network: "linkedin", language: "english", proficiency: "native or bilingual" }],
      identities: [{ network: "linkedin", type: "gender", value: "female" }],
      relationships: [],
      religion: [],
      political_party: [],
      identifications: [],
      skills: ["product management", "sql", "javascript", "agile"],
      interests: [{ value: 3, name: "technology" }],
    },
  },
};
