const { performSearch } = require("../utils");

module.exports = {
  key: "school",
  noun: "School",
  display: {
    label: "Find School",
    description: "Finds a school by domain or profile URL.",
  },
  operation: {
    // Don't let Zapier auto-trim/cast our string inputs — keep behavior predictable.
    cleanInputData: false,
    inputFields: [
      { key: "domain", label: "Domain", type: "string", helpText: "The school's website domain, e.g. stanford.edu." },
      { key: "profile_url", label: "Profile URL", type: "string", helpText: "The school's LinkedIn (or other) profile URL." },
    ],
    perform: performSearch("school"),
    // A school is a company record with is_school: true — same shape as /search?type=company.
    sample: {
      id: "sampleSchoolId01",
      updated_at: null,
      created_at: "2026-01-25T08:45:02.000Z",
      domain: "stanford.edu",
      is_school: true,
      type: null,
      company_size: null,
      company_size_range: null,
      founded: null,
      semrush_global_rank: null,
      stock_symbol: null,
      stock_exchange: null,
      titles: [],
      specialities: [],
      technologies: [],
      industries: [{ name: "HIGHER_EDUCATION" }],
      names: [{ first_name: "stanford university", middle_name: null, last_name: null, source: "linkedin" }],
      profiles: [
        {
          created_at: "2026-01-25T08:45:02.000Z",
          profile_created_at: null,
          type: "school",
          profile_id: "162040",
          network: "linkedin",
          username: null,
          url: "linkedin.com/school/stanford-university",
          profile_picture: null,
          cover_picture: null,
          verified: null,
          private: null,
          followers_count: null,
          following_count: null,
          posts_count: null,
          groups_count: null,
          favourites_count: null,
          description: null,
        },
      ],
      lighthouse_scores: [],
      locations: [{ address: null, region: null, zip: null, time_zone: null, network: "internal", city: "stanford", country: "united states", continent: null, state: "ca" }],
      repositories: [],
      websites: ["https://www.stanford.edu"],
      patents: [],
    },
  },
};
